# Generated by Django 3.2.16 on 2024-05-10 13:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=True, help_text='Флаг публикации на сайте')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата публикации может быть использована при сортировке', verbose_name='Дата создания')),
                ('title', models.CharField(help_text='Название категории, не более 256 символов, обязательное поле', max_length=256, verbose_name='Название')),
                ('description', models.TextField(help_text='Описание публикации, обязательное поле', verbose_name='Описание')),
                ('slug', models.SlugField(help_text='Уникальная ссылка на категорию, не более 256 символов, обязательное поле', max_length=64, unique=True, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'категорию',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=True, help_text='Флаг публикации на сайте')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата публикации может быть использована при сортировке', verbose_name='Дата создания')),
                ('title', models.CharField(help_text='Название географической метки, не более 256 символов, обязательное поле', max_length=256, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'географическую метку',
                'verbose_name_plural': 'Географические метки',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=True, help_text='Флаг публикации на сайте')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата публикации может быть использована при сортировке', verbose_name='Дата создания')),
                ('title', models.CharField(help_text='Название публикации, не более 256 символов, обязательное поле', max_length=256, verbose_name='Название')),
                ('text', models.TextField(help_text='Текст публикации, обязательное поле', verbose_name='Текст публикации')),
                ('pub_date', models.DateTimeField(help_text='Дата публикации, обязательное поле', verbose_name='Дата публикации')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='blog.category', verbose_name='Категория')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='blog.location', verbose_name='Локация')),
            ],
            options={
                'verbose_name': 'публикацию',
                'verbose_name_plural': 'Публикации',
            },
        ),
    ]
