# Generated by Django 3.2.16 on 2024-06-24 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='is_published',
        ),
    ]
